name: Keeping Go up to date
on:
  schedule:
    - cron: 47 4 * * *
jobs:
  fresh_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - uses: jmhodges/ensure_latest_go@action
        id: ensure_go
        with:
          dockerfiles:
            - ./Dockerfile
      - run: echo "##[set-output name=pr_title;]updating to latest Go release ${{ steps.ensure_go.outputs.go_version}}"
        id: pr_title_maker
      - name: Create pull request
        uses: peter-evans/create-pull-request@v1.5.2
        env:
          PULL_REQUEST_TITLE: ${{ steps.pr_title_maker.outputs.pr_title }}
          COMMIT_MESSAGE: ${{ steps.pr_title_maker.outputs.pr_title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
